apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-mongo
  template:
    metadata:
      labels:
        app: query-mongo
    spec:
      containers:
        - name: query-mongo
          image: mongo