apiVersion: v1
kind: Service
metadata:
  name: query-mongo-service
spec:
  type: ClusterIP
  selector:
    app: query-mongo
  ports:
    - name: query-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017